# Generated by Django 6.0.4 on 2026-05-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_group_teacher_alter_studentprofile_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month'], name='main_paymen_student_f2822f_idx'),
        ),
    ]
